### ISSUE TITLE
ESP07 Module PCB View

### ISSUE THREAD

**Issue by jellyfishcoder** [ydonnelly/ESP8266_fritzing#12]
In PCB view for ESP07, the labels (and mappings) for gpis 4 and 5 are switched.

**Comment by edelrosespol** [comment]
Same problem found, but it was not updated.

**Comment by Damian-R-Smith** [comment]
There is an open pull request submitted in march which looks to have addressed this issue. 

https://github.com/ydonnelly/ESP8266_fritzing/pull/13

**Comment by ydonnelly** [comment]
Pull request #13 now merged, let me know if the issue is resolved on your end.
