### ISSUE TITLE
ESP-01 module variation

### ISSUE THREAD

**Issue by pastcompute** [ydonnelly/ESP8266_fritzing#2]
Hi! Thanks for this part.
On my ESP-01 (and from what I have seen on the Internet, other people) fritzing pin4 is in fact connected to /RESET not to GPIO-16.  This pin works as a reset on my module.
In order to get deep sleep (GPIOto work on my module I had to do the "solder a wire from GPIO0 to XPD_DCDC" trick.
Although AFAICT the only way to really tell apart from using a good magnifier is wire up the module and observe shorting (fritzing pin4) to earth actually resets the module...

**Comment by ydonnelly** [comment]
Thanks for the comment!
I used one of the earlier ESP-01 boards, which seems to be a copy of the application note on page 7 of the datasheet, where GPIO_16 is connected to pin 8 XPD_DCDC. It seems that most people are receiving boards with RSTn on that pin now, so I have updated the part.
