### ISSUE TITLE
ESP 201

### ISSUE THREAD

**Issue by uamp** [ydonnelly/ESP8266_fritzing#5]
Hi, thank you for the great work! I don't suppose I could persuade you to draw the ESP201 (http://smarpl.com/sites/default/files/images/ESP8266-ESP-201-pin-reference-v01.png).
I have a circuit using this that I want to put on instructables, but lack the ability to draw svg files!

**Comment by uamp** [comment]
![esp8266-esp-201-pin-reference-v01](https://cloud.githubusercontent.com/assets/12737443/8393055/4304b3e2-1cf6-11e5-9579-b359a7a5662f.png)

**Comment by ydonnelly** [comment]
I have just committed an attempt at this board, I did get an error with the PCB view I have to look into but that shouldn't affect the breadboard or schematic views.

**Comment by ydonnelly** [comment]
Fixed!

**Comment by uamp** [comment]
What a star! Thank you so much.  Hopefully it will benefit lots of others too.
