### ISSUE TITLE
ESP8266 VARIANT 12 issue

### ISSUE THREAD

**Issue by simonepsp** [ydonnelly/ESP8266_fritzing#6]
Hi,
I've a problem with variant 12 of your fritzing part.
When I do DRC check fritzing shows a lot of errors on your component. Even without wires connected!

I'm using fritzing 0.9.2
Here's a screenshot:
![2015-07-25_11-33-01](https://cloud.githubusercontent.com/assets/11884948/8888883/2ec92a08-32c1-11e5-8aa0-968d2a9372c4.jpg)

Could you please fix it?
Thanks for your help

**Comment by ydonnelly** [comment]
Commit 23 has a new PCB view that passes DRC. Thanks for reporting!
